### ISSUE TITLE
need help !!!!!

### ISSUE THREAD

**Issue by MagKartik** [BarbieBarbsson/GenerationenRP#1]
heyy , i loved your file a lot but i am facing language issue can please provide the same files in english because you have translated the EN files in your local language . please help !!!!!!!!!!!!

**Comment by TricksterClown** [comment]
@MagKartik  can you give me your discord ? wanna have a chat regarding  a huge indian project

**Comment by MagKartik** [comment]
@MagKartik#9949 Sent from Mail for Windows 10 From: TricksterClownSent: Tuesday, June 2, 2020 5:35 PMTo: BarbieBarbsson/GenerationenRPCc: MagKartik; MentionSubject: Re: [BarbieBarbsson/GenerationenRP] need help !!!!! (#1) @MagKartik can you give me your discord ? wanna have a chat regarding a huge indian project—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MagKartik** [comment]
> @MagKartik can you give me your discord ? wanna have a chat regarding a huge indian project

MagKartik#9949
